### ISSUE TITLE
Placing an object with a solid top on the border of the world causes a crash

### ISSUE THREAD

**Issue by ChrisThor** [ChrisThor/SpaceGame#22]
```
Traceback (most recent call last):
  File "C:/Users/[...]/main.py", line 485, in <module>
    main()
  File "C:/Users/[...]/main.py", line 299, in main
    running, world_zoom_factor = template_planet_surface.access_surface(background, center_x, center_y, world_zoom_factor, space.tickrate)
  File "C:\Users\[...]\world.py", line 192, in access_surface
    self.dismantle_blocks(center_x, center_y, zoom_factor, tickrate, background)
  File "C:\Users\[...]\world.py", line 490, in dismantle_blocks
    block[0].solid_top = True
TypeError: 'NoneType' object is not subscriptable

```

**Comment by ChrisThor** [comment]
That also happens with normal objects now
